package com.manage.po;

// Generated 2016-4-25 15:17:59 by Hibernate Tools 3.2.2.GA

/**
 * FUserinfo generated by hbm2java
 */
public class FUserinfo implements java.io.Serializable {

	private String uidd;
	private String usercode;
	private String password;

	public FUserinfo() {
	}

	public FUserinfo(String uidd) {
		this.uidd = uidd;
	}

	public FUserinfo(String uidd, String usercode, String password) {
		this.uidd = uidd;
		this.usercode = usercode;
		this.password = password;
	}

	public String getUidd() {
		return this.uidd;
	}

	public void setUidd(String uidd) {
		this.uidd = uidd;
	}

	public String getUsercode() {
		return this.usercode;
	}

	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
